// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateTask(arg1:main.Task):Promise<string>;

export function GetProjects():Promise<Array<main.ProjectStructQuery>>;

export function Greet(arg1:string):Promise<string>;
