// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateDb():void;

export function CreateTask(arg1:main.task):Promise<string>;

export function GetFileList(arg1:string):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;
