// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClockIn(arg1:number):void;

export function CreateMainBlock(arg1:main.Task):Promise<Array<main.Task>>;

export function GetProjects():Promise<Array<main.ProjectStructQuery>>;

export function GetTasks(arg1:number):Promise<Array<main.Task>>;

export function Greet(arg1:string):Promise<string>;

export function UpdateTask(arg1:main.Task):void;
